### ISSUE TITLE
I implemented a recursive index.md render-er to show every readme you have, in order listed in main README, and hosted it on gh-pages

### ISSUE THREAD

**Issue by juliusakula** [jshomes/learning-resources#15]
## http://karma-tech-consulting.github.io/learning-resources/#/

I was looking at the project and it was a lot of traversing directories to try to get the big picture of the curriculum listed, So I made an HTML page to show it all. How it works is, on the README.md file in the root directory parses everything beginning with `1.` after `## Content`. It takes the link from the bullet point and does an http request to get the markdown, and repeats that markdown in the order originally listed in the main README. Its done with bootstrap, AngularJS and AngularMD.

I wanted to parse it further, so that youtube videos are embedded, courses have an image, and links to articles and books have iframes. And wanted to add the ability to check each item off (input checkbox), with a cookie or login system to track which items you check completed. But I didn't want to take the thing too far without first seeing if something like that is wanted.

Oh, a second thing that's been done is I created a gh-pages branch with an index.html file, which magically hosts it on gh-pages! So you can see it at <org/user-name>.github.io/<repo-name>, So if you want to merge these changes, I would suggest adding jshomes.github.io/learning-resources to the README.md file somewhere prominent.

Huge fan btw, @ericelliott

**Comment by ericelliott** [comment]
Hi @juliusakula 

Impressive start. Have you had a look at the [JSHomes Platform](https://github.com/jshomes/JSHomes-Platform) repository? Specifically [the dev meta issue](https://github.com/jshomes/JSHomes-Platform/issues/4).

This learning resources repo is really intended for content, whereas the JSHomes Platform repo is for courseware. If you take a peek over there, you can get a sense of where we're going with the software platform.

One of the things we really need to build is something like what you have in mind here: A way to browse hierarchies of Markdown in a nicely structured HTML courseware UI, which should definitely include features like you mentioned - the ability for the courseware to keep track of your progress, support for embedding videos, and so on.

We're building with ES6 on Node, Express, & React (not Angular, sorry), but if you want to abstract the recursive markdown walker and render in React components, we're definitely open to this type of help.

Use [class free style ES6](https://github.com/ericelliott/class-free-javascript-style) & React. See [Baby's First Reaction](https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd) to learn a little about building stateless, class-free React components.

Does that sound interesting to you?

**Comment by juliusakula** [comment]
Hey Eric,

Sorry for the delay in response - long story short I don't think right now I'd be the right person for something with ES6 & React, I'm currently switching my world from Apache & PHP to NodeJS + Express, and have 3-4 side projects related with that, plus my freelance clients plus my full time job

React is really cool and it's the future, it'll be around long enough for me to adopt it. I like the fundamentals (virtual jsDOM) but, as a freelancer I market that I'm quick-to-develop angular applications, so I'm going to play to that strength for a little while. In the future if I dive into React and help is still needed, I'll try to contribute here

Cheers

**Comment by ericelliott** [comment]
No worries. Thanks for caring enough to open a PR. I hope you'll get a chance to contribute in the future. =)
