### ISSUE TITLE
Link to awesome?

### ISSUE THREAD

**Issue by kamlekar** [jshomes/learning-resources#22]
Can we link this repo to [awesome](https://github.com/sindresorhus/awesome)?

_There are some guidelines to follow._

**Comment by ericelliott** [comment]
I'm not sure what you're asking.

Are you asking if we should link to the list of awesome lists from this repo?

If so, where would the link fit?

If you're asking if we can link to this list from the list of awesome lists... yes. =)

**Comment by kamlekar** [comment]
I was actually asking the former one but as you explained that it is not possible. I am okay with your latter suggestion too.

**Comment by ericelliott** [comment]
I think it's possible... just not sure where to link from...
