### ISSUE TITLE
Absence of browser internals

### ISSUE THREAD

**Issue by R1ZZU** [jshomes/learning-resources#27]
Hey, guys! Just wondering why there is no browser internals section? Are you interested in covering this topic?

**Comment by ericelliott** [comment]
Do you have a suggestion for it?

**Comment by R1ZZU** [comment]
There is a lot of great articles/talks listed [here](https://developers.google.com/web/updates/2012/04/Round-up-of-Web-Browser-Internals-Resources?hl=en), but I think [How Browsers Work: Behind the scenes of modern web browserss](http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/) is the best. It covers pretty much every step in how browser renders web pages and explains all this special magic happening inside browser

**Comment by ericelliott** [comment]
I think one link is enough. A typical web programmer doesn't need a deep dive on browser internals. A very small percentage of programming students end up building browser engines. Most of the value comes from understanding the process and applying it to writing better performing code to run in the browser.

Maybe it should go in "Fundamentals" after "How Does the Internet Work?"

**Comment by R1ZZU** [comment]
Yes, I agree with you, I'll submit PR soon if you don't mind

**Comment by ericelliott** [comment]
:+1: :fire: :guitar: :notes:
