### ISSUE TITLE
Learn JavaScript interactively (codermania.com)

### ISSUE THREAD

**Issue by Elfoslav** [jshomes/learning-resources#6]
People like [CodeCademy](http://www.codecademy.com/), but I believe that e-learning can be done better. That's why I have created [CoderMania](http://www.codermania.com) where people can learn JavaScript by the best way I can imagine - reading theory, playing with examples of code in code editor, doing exercises and assignments. That's the way I would want to learn when I started learning to code.

**Comment by ericelliott** [comment]
Right idea, but I'm not sure the content is modular enough to fit into our learning tracks.
